[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["cd Site && npm ci"]

[phases.build]
cmds = ["cd Site && npm run build"]

[start]
# serve the compiled files; keep it simple
cmd = "npx http-server Site/dist/flightdeck -p $PORT -c-1"