const app = document.querySelector('#app');
let me = null, workspace = { groups: [] }, editing = null, currentSearchMatches = [];
const api = async (url, options = {}) => {
  const response = await fetch(url, { credentials: 'same-origin', headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options });
  if (response.status === 401 && url !== '/api/auth/refresh') {
    const refreshed = await fetch('/api/auth/refresh', { method: 'POST', credentials: 'same-origin' });
    if (refreshed.ok) return api(url, options);
  }
  const body = response.status === 204 ? null : await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.error || 'Something went wrong.');
  return body;
};
const esc = (v = '') => String(v).replace(/[&<>'"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c]));
const initials = title => title.split(/\s+/).map(x => x[0]).join('').slice(0, 2) || '↗';
const googleFaviconURL = url => url ? `https://www.google.com/s2/favicons?sz=64&domain_url=${encodeURIComponent(url)}` : '';
const pageFaviconURL = url => url ? `/api/favicon?url=${encodeURIComponent(url)}` : '';
window.loadFallbackFavicon = image => { const next = image.dataset.googleSrc; if (!next) { image.hidden = true; return; } image.dataset.googleSrc = ''; image.src = next; };
const searchEngineCookie = 'flightdeck-search-engine';
const searchEngine = () => document.cookie.split('; ').find(row => row.startsWith(searchEngineCookie+'='))?.split('=')[1] === 'duckduckgo' ? 'duckduckgo' : 'google';
const setSearchEngine = engine => { document.cookie = `${searchEngineCookie}=${engine}; Max-Age=31536000; Path=/; SameSite=Lax`; };
const searchURL = query => searchEngine() === 'duckduckgo' ? `https://duckduckgo.com/?q=${encodeURIComponent(query)}` : `https://www.google.com/search?q=${encodeURIComponent(query)}`;
const envEmoji = name => ({ prod:'🟢', production:'🟢', dev:'🔴', development:'🔴', test:'🟠', tst:'🟠', qa:'🔵', local:'🟡', ci:'🟣' })[name.toLowerCase()] || '•';
function toast(message) { document.querySelector('.notice')?.remove(); const n = document.createElement('div'); n.className='notice'; n.textContent=message; document.body.append(n); setTimeout(()=>n.remove(),3600); }
function setTheme() { document.body.classList.toggle('dark', localStorage.flightdeckTheme === 'dark'); }
function toggleTheme() { localStorage.flightdeckTheme = localStorage.flightdeckTheme === 'dark' ? 'light' : 'dark'; setTheme(); }
function authScreen(signup = false) {
  app.innerHTML = `<main class="auth"><div class="brand">FlightDeck</div><h1>${signup ? 'Create your workspace' : 'Welcome back'}</h1><p class="subtle">Your personal browser launcher.</p><form id="auth-form"><label class="field ${signup ? '' : 'hidden'}"><span>Name</span><input name="name" autocomplete="name" ${signup ? 'required' : 'disabled'}></label><label class="field"><span>Email</span><input type="email" name="email" autocomplete="email" required></label><label class="field"><span>Password</span><input type="password" name="password" autocomplete="${signup?'new-password':'current-password'}" minlength="10" required></label><button class="button primary" type="submit">${signup ? 'Create account' : 'Log in'}</button></form><p class="subtle">${signup ? 'Already have an account?' : 'Need an account?'} <button class="link" id="switch-auth">${signup ? 'Log in' : 'Sign up'}</button></p></main>`;
  document.querySelector('#switch-auth').onclick = () => authScreen(!signup);
  document.querySelector('#auth-form').onsubmit = async e => { e.preventDefault(); const f = Object.fromEntries(new FormData(e.target)); try { const data = await api(`/api/auth/${signup?'signup':'login'}`, { method:'POST', body:JSON.stringify(f) }); me=data.user; await load(); } catch (err) { toast(err.message); } };
}
async function load() { workspace = await api('/api/workspace'); render(); }
function render() {
  const groups = workspace.groups;
  app.innerHTML = `<div class="shell"><header class="topbar"><div><div class="brand">FlightDeck</div><div class="subtle">${groups.length} tab group${groups.length===1?'':'s'} · ${groups.reduce((n,g)=>n+g.tabs.length,0)} tabs</div></div><div class="top-actions"><button class="icon-button" id="theme">${document.body.classList.contains('dark')?'☀️':'🌙'}</button><button class="button" id="logout">Log out</button></div></header><main><div class="search"><input id="search" placeholder="Search your tabs, URLs, or type a web search" autocomplete="off"><div class="search-engines" aria-label="Web search engine"><button class="search-engine ${searchEngine()==='duckduckgo'?'selected':''}" type="button" data-search-engine="duckduckgo" aria-pressed="${searchEngine()==='duckduckgo'}">DuckDuckGo</button><button class="search-engine ${searchEngine()==='google'?'selected':''}" type="button" data-search-engine="google" aria-pressed="${searchEngine()==='google'}">Google</button></div><div class="search-results" id="results" hidden></div></div><div id="groups">${groups.length ? groups.map(groupMarkup).join('') : '<div class="empty">No tab groups yet. Add your first group to start launching.</div>'}</div><button class="button" id="add-group">+ Add tab group</button></main></div>`;
  document.querySelector('#theme').onclick=()=>{toggleTheme();render()}; document.querySelector('#logout').onclick=logout;
  document.querySelector('#add-group').onclick=()=>groupDialog(); document.querySelectorAll('[data-search-engine]').forEach(button=>button.onclick=()=>{setSearchEngine(button.dataset.searchEngine);render()}); bindWorkspace(); bindSearch();
}
function groupMarkup(g) { return `<section class="group" data-group="${g.id}"><div class="group-head"><button class="group-name" data-edit-group="${g.id}">${esc(g.title)}</button></div><div class="card-row">${g.tabs.map(t=>tabMarkup(t,g.id)).join('')}<button class="add-card" data-add-tab="${g.id}"><div class="card-top"><div class="icon">+</div><div><div class="card-title">Add tab</div><div class="url">Add a URL to this group</div></div></div></button></div></section>`; }
function tabMarkup(t,gid) { const primary=t.environments[0]; return `<article class="card" data-launch="${t.id}"><div class="card-top"><div class="icon">${primary?`<img class="favicon" src="${pageFaviconURL(primary.url)}" data-google-src="${googleFaviconURL(primary.url)}" alt="" onerror="loadFallbackFavicon(this)">`:''}<span class="${primary?'':'fallback'}">${esc(initials(t.title))}</span></div><div><div class="card-title">${esc(t.title)}</div><div class="url">${esc(primary?.url || 'No environment')}</div></div></div><div class="card-bottom"><div class="chips">${t.environments.map(e=>`<button class="chip env-${esc(e.name.toLowerCase())}" type="button" data-launch-env="${e.id}">${esc(e.name)}</button>`).join('')}</div><button class="icon-button" data-edit-tab="${t.id}" title="Edit tab">✎</button></div></article>`; }
function bindWorkspace() {
  document.querySelectorAll('[data-launch]').forEach(el=>el.onclick=e=>{ if(e.target.closest('button')) return; const t=findTab(el.dataset.launch); if(t?.environments[0]) window.open(t.environments[0].url,'_blank','noopener'); });
  document.querySelectorAll('[data-add-tab]').forEach(el=>el.onclick=()=>tabDialog(el.dataset.addTab));
  document.querySelectorAll('[data-edit-tab]').forEach(el=>el.onclick=()=>tabDialog(null,findTab(el.dataset.editTab)));
  document.querySelectorAll('[data-edit-group]').forEach(el=>el.onclick=()=>groupDialog(findGroup(el.dataset.editGroup)));
  document.querySelectorAll('[data-launch-env]').forEach(el=>el.onclick=e=>{e.stopPropagation();const environment=findEnvironment(el.dataset.launchEnv);if(environment)window.open(environment.url,'_blank','noopener')});
}
function bindSearch() { let timer; const input=document.querySelector('#search'), results=document.querySelector('#results'); input.oninput=()=>{clearTimeout(timer);const q=input.value.trim();currentSearchMatches=[];if(!q){results.hidden=true;return}timer=setTimeout(async()=>{try{const data=await api('/api/search?q='+encodeURIComponent(q));currentSearchMatches=data.tabs;results.innerHTML=data.tabs.length?data.tabs.map(t=>`<button class="result" data-result="${t.id}"><strong>${esc(t.title)}</strong><br><span class="subtle">${esc(t.environments.map(e=>e.url).join(' · '))}</span></button>`).join(''):`<div class="result subtle">No matching tabs. Press Enter to search the web with ${searchEngine()==='duckduckgo'?'DuckDuckGo':'Google'}.</div>`;results.hidden=false;results.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>{const t=data.tabs.find(t=>t.id===b.dataset.result);if(t.environments[0])window.open(t.environments[0].url,'_blank','noopener')})}catch(e){toast(e.message)}},180)}; input.onkeydown=e=>{if(e.key==='Enter'){const q=input.value.trim();if(q&&!currentSearchMatches.length){window.open(searchURL(q),'_blank','noopener')}}}; }
function groupDialog(g) { if(!g){modal(`<h2>Create tab group</h2><p>Keep related sites together.</p><form id="group-form"><label class="field"><span>Group title</span><input name="title" required maxlength="120" autofocus></label><div class="dialog-actions"><button class="button" type="button" data-close>Cancel</button><button class="button primary">Create</button></div></form>`);document.querySelector('#group-form').onsubmit=async e=>{e.preventDefault();await mutate('/api/groups',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});closeModal()};return;} editing=g; modal(`<h2>Manage ${esc(g.title)}</h2><p>Rename the group or arrange its tabs.</p><form id="group-form"><label class="field"><span>Group title</span><input name="title" value="${esc(g.title)}" required maxlength="120"></label><div class="tab-order">${g.tabs.length?g.tabs.map((t,i)=>`<div class="tab-order-row"><span class="tab-order-name">${esc(t.title)}</span><div><button class="icon-button" type="button" data-order-tab="${t.id}" data-direction="up" ${i===0?'disabled':''}>↑</button><button class="icon-button" type="button" data-order-tab="${t.id}" data-direction="down" ${i===g.tabs.length-1?'disabled':''}>↓</button></div></div>`).join(''):'<div class="subtle">No tabs yet.</div>'}</div><div class="dialog-actions"><button class="button danger" type="button" id="delete">Delete group</button><button class="button" type="button" data-close>Cancel</button><button class="button primary">Save</button></div></form>`);document.querySelector('#group-form').onsubmit=async e=>{e.preventDefault();await mutate(`/api/groups/${g.id}`,{method:'PUT',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});closeModal()};document.querySelector('#delete').onclick=async()=>{if(confirm('Delete this group and every tab in it?')){await mutate(`/api/groups/${g.id}`,{method:'DELETE'});closeModal()}};document.querySelectorAll('[data-order-tab]').forEach(b=>b.onclick=async()=>{try{await api(`/api/tabs/${b.dataset.orderTab}/move`,{method:'POST',body:JSON.stringify({direction:b.dataset.direction})});await load();groupDialog(findGroup(g.id))}catch(e){toast(e.message)}}); }
function environmentRow(e={name:'prod',url:''}) { return `<div class="environment"><input name="env-name" value="${esc(e.name)}" placeholder="Name e.g. prod" required><input name="env-url" value="${esc(e.url)}" placeholder="https://…" required><button class="icon-button remove-env" type="button">×</button></div>`; }
function tabDialog(groupID, t) { const g=groupID?findGroup(groupID):null; modal(`<h2>${t?'Edit tab':'Add tab'}</h2><p>${t?'Update the title and its environments.':'Add a launch target to '+esc(g.title)+'.'}</p><form id="tab-form"><label class="field"><span>Tab title</span><input name="title" value="${esc(t?.title||'')}" required maxlength="120" autofocus></label><div><span class="subtle">Environments</span><div id="environments">${(t?.environments?.length?t.environments:[{name:'prod',url:''}]).map(environmentRow).join('')}</div><button class="button" type="button" id="add-env">+ Add environment</button></div><div class="dialog-actions">${t?'<button class="button danger" type="button" id="delete-tab">Delete tab</button>':''}<button class="button" type="button" data-close>Cancel</button><button class="button primary">Save</button></div></form>`); const envs=document.querySelector('#environments'); const bind=()=>envs.querySelectorAll('.remove-env').forEach(b=>b.onclick=()=>{if(envs.children.length>1)b.parentElement.remove();else toast('A tab needs one environment.')}); bind();document.querySelector('#add-env').onclick=()=>{envs.insertAdjacentHTML('beforeend',environmentRow({name:'dev',url:''}));bind()};document.querySelector('#tab-form').onsubmit=async e=>{e.preventDefault();const form=new FormData(e.target), names=[...document.querySelectorAll('[name="env-name"]')],urls=[...document.querySelectorAll('[name="env-url"]')];const payload={title:form.get('title'),environments:names.map((n,i)=>({name:n.value,url:urls[i].value}))};await mutate(t?`/api/tabs/${t.id}`:`/api/groups/${groupID}/tabs`,{method:t?'PUT':'POST',body:JSON.stringify(payload)});closeModal()};document.querySelector('#delete-tab')?.addEventListener('click',async()=>{if(confirm('Delete this tab?')){await mutate(`/api/tabs/${t.id}`,{method:'DELETE'});closeModal()}}); }
function modal(content) { document.querySelector('.modal')?.remove(); const el=document.createElement('div');el.className='modal';el.innerHTML=`<div class="dialog">${content}</div>`;document.body.append(el);el.onclick=e=>{if(e.target===el)closeModal()};el.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModal); }
function closeModal(){document.querySelector('.modal')?.remove()}; async function mutate(url,options){try{await api(url,options);await load()}catch(e){toast(e.message)}}; function findGroup(id){return workspace.groups.find(g=>g.id===id)};function findTab(id){for(const g of workspace.groups){const t=g.tabs.find(t=>t.id===id);if(t)return t}}function findEnvironment(id){for(const g of workspace.groups){for(const t of g.tabs){const e=t.environments.find(e=>e.id===id);if(e)return e}}}
async function logout(){await api('/api/auth/logout',{method:'POST'});me=null;authScreen()}
async function boot(){setTheme();try{const d=await api('/api/auth/me');me=d.user;await load()}catch{authScreen()}}boot();
