@userId = a6fddb43-9861-11f0-ba26-0242ac120003
@tabGroupId = c6f14643-9861-11f0-ba26-0242ac120003
@tabId = 20ff62f3-9869-11f0-ba26-0242ac120003

@hamish=c7f4f096-9930-11f0-ba26-0242ac120003

### Health Check
GET http://localhost:3000/health
Accept: application/json

### List Constants
GET http://localhost:3000/consts/environments
Accept: application/json

### Create User
POST http://localhost:3000/users
Content-Type: application/json
Accept: application/json

{
  "name": "Hamish"
}

### Delete User
DELETE http://localhost:3000/users
Accept: application/json
user_id: {{userId}}

### Get User Tab Groups
GET http://localhost:3000/users/tab-groups
Accept: application/json
user_id: {{userId}}

### Get User Summary
GET http://localhost:3000/users/summary
Accept: application/json
user_id: {{userId}}

### Get Workspace
GET http://localhost:3000/users/workspace
Accept: application/json
user_id: {{userId}}

### Create Tab Group
POST http://localhost:3000/tab-groups
Content-Type: application/json
Accept: application/json
user_id: {{userId}}

{
  "title": "Connectwise"
}

### Rename Tab Group
PATCH http://localhost:3000/tab-groups/{{tabGroupId}}
Content-Type: application/json
Accept: application/json
user_id: {{userId}}

{
  "title": "Updated Tab Group"
}

### Delete Tab Group
DELETE http://localhost:3000/tab-groups/{{tabGroupId}}
Accept: application/json
user_id: {{userId}}

### Get Tab Group Summary
GET http://localhost:3000/tab-groups/summary
Accept: application/json
user_id: {{userId}}

### Get Tabs For Tab Group
GET http://localhost:3000/tab-groups/{{tabGroupId}}/tabs
Accept: application/json
user_id: {{userId}}

### Create Tab
POST http://localhost:3000/tabs
Content-Type: application/json
Accept: application/json
user_id: {{userId}}

{
  "tabGroupId": "{{tabGroupId}}",
  "title": "Connectwise",
  "environment": {
    "name": "prd",
    "url": "https://connectwise.example.com"
  }
}

### Rename Tab
PATCH http://localhost:3000/tabs/{{tabId}}
Content-Type: application/json
Accept: application/json
user_id: {{userId}}

{
  "title": "Updated Tab"
}

### Delete Tab
DELETE http://localhost:3000/tabs/{{tabId}}
Accept: application/json
user_id: {{userId}}

### Create Environment
POST http://localhost:3000/environments
Content-Type: application/json
Accept: application/json
user_id: {{userId}}

{
  "tabId": "{{tabId}}",
  "name": "tst",
  "url": "https://example.com"
}

### Update Environment
PATCH http://localhost:3000/environments/{{environmentId}}
Content-Type: application/json
Accept: application/json
user_id: {{userId}}

{
  "name": "Staging",
  "url": "https://staging.example.com"
}

### Delete Environment
DELETE http://localhost:3000/environments/{{environmentId}}
Accept: application/json
user_id: {{userId}}

### List Environments For Tab
GET http://localhost:3000/environments/tabs/{{tabId}}
Accept: application/json
user_id: {{userId}}
