@userId = a6fddb43-9861-11f0-ba26-0242ac120003
@tabGroupId = c6f14643-9861-11f0-ba26-0242ac120003
@tabId = 20ff62f3-9869-11f0-ba26-0242ac120003

@hamish=c7f4f096-9930-11f0-ba26-0242ac120003

@host = flightdeck.site/api

### Health Check
GET http://{{host}}/health
Accept: application/json

### List Constants
GET http://{{host}}/consts/environments
Accept: application/json

### List Users
GET http://{{host}}/users
Accept: application/json

### Create User
POST http://{{host}}/users
Content-Type: application/json
Accept: application/json

{
  "name": "Logan"
}

### Delete User
DELETE http://{{host}}/users
Accept: application/json
user_id: {{userId}}

### Get User Tab Groups
GET http://{{host}}/users/tab-groups
Accept: application/json
user_id: {{userId}}

### Get User Summary
GET http://{{host}}/users/summary
Accept: application/json
user_id: {{userId}}

### Get Workspace
GET http://{{host}}/users/workspace
Accept: application/json
user_id: {{userId}}

### Create Tab Group
POST http://{{host}}/tab-groups
Content-Type: application/json
Accept: application/json
user_id: {{userId}}

{
  "title": "Connectwise"
}

### Rename Tab Group
PATCH http://{{host}}/tab-groups/{{tabGroupId}}
Content-Type: application/json
Accept: application/json
user_id: {{userId}}

{
  "title": "Updated Tab Group"
}

### Delete Tab Group
DELETE http://{{host}}/tab-groups/{{tabGroupId}}
Accept: application/json
user_id: {{userId}}

### Get Tab Group Summary
GET http://{{host}}/tab-groups/summary
Accept: application/json
user_id: {{userId}}

### Get Tabs For Tab Group
GET http://{{host}}/tab-groups/{{tabGroupId}}/tabs
Accept: application/json
user_id: {{userId}}

### Create Tab
POST http://{{host}}/tabs
Content-Type: application/json
Accept: application/json
user_id: {{userId}}

{
  "tabGroupId": "{{tabGroupId}}",
  "title": "Connectwise",
  "environment": {
    "name": "prd",
    "url": "https://connectwise.example.com"
  }
}

### Rename Tab
PATCH http://{{host}}/tabs/{{tabId}}
Content-Type: application/json
Accept: application/json
user_id: {{userId}}

{
  "title": "Updated Tab"
}

### Delete Tab
DELETE http://{{host}}/tabs/{{tabId}}
Accept: application/json
user_id: {{userId}}

### Create Environment
POST http://{{host}}/environments
Content-Type: application/json
Accept: application/json
user_id: {{userId}}

{
  "tabId": "{{tabId}}",
  "name": "tst",
  "url": "https://example.com"
}

### Update Environment
PATCH http://{{host}}/environments/{{environmentId}}
Content-Type: application/json
Accept: application/json
user_id: {{userId}}

{
  "name": "Staging",
  "url": "https://staging.example.com"
}

### Delete Environment
DELETE http://{{host}}/environments/{{environmentId}}
Accept: application/json
user_id: {{userId}}

### List Environments For Tab
GET http://{{host}}/environments/tabs/{{tabId}}
Accept: application/json
user_id: {{userId}}
