name: Trigger Coolify Site Deploy

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  call-coolify:
    runs-on: [self-hosted]
    steps:
      - name: Hit Coolify deploy endpoint
        env:
          COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}
          URL: "http://10.10.10.9:8000/api/v1/deploy?uuid=fkgg4sk8s4k0kwcwos8ccs0c&force=false"
        run: |
          curl --fail --show-error --silent \
               --retry 1 --retry-delay 2 --retry-connrefused \
               -H "Authorization: Bearer ${COOLIFY_TOKEN}" \
               "$URL"
